name: poison
channels:
  - pytorch
  - conda-forge
dependencies:
  - attrs=21.4.0=pyhd8ed1ab_0
  - brotli=1.0.9=h3422bc3_6
  - brotli-bin=1.0.9=h3422bc3_6
  - ca-certificates=2021.10.8=h4653dfc_0
  - certifi=2021.10.8=py38h10201cd_1
  - cffi=1.15.0=py38hc67bbb8_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - fonttools=4.28.5=py38hea4295b_0
  - freetype=2.10.4=h17b34a0_1
  - future=0.18.2=py38h10201cd_4
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - jbig=2.1=h3422bc3_2003
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h27ca646_0
  - kiwisolver=1.3.2=py38h1670459_1
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libblas=3.9.0=13_osxarm64_openblas
  - libbrotlicommon=1.0.9=h3422bc3_6
  - libbrotlidec=1.0.9=h3422bc3_6
  - libbrotlienc=1.0.9=h3422bc3_6
  - libcblas=3.9.0=13_osxarm64_openblas
  - libcxx=12.0.1=h168391b_1
  - libdeflate=1.8=h3422bc3_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=13_osxarm64_openblas
  - libopenblas=0.3.18=openmp_h5dd58f0_0
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.18.1=hccf11d3_0
  - libtiff=4.3.0=h74060c4_2
  - libwebp-base=1.2.2=h3422bc3_0
  - libzlib=1.2.11=hee7b306_1013
  - llvm-openmp=12.0.1=hf3c4609_1
  - lz4-c=1.9.3=hbdafb3b_1
  - matplotlib=3.5.1=py38h150bfb4_0
  - matplotlib-base=3.5.1=py38hb140015_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=hc470f4d_0
  - ninja=1.10.2=hc021e02_1
  - numpy=1.22.0=py38h9d822b3_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=3.0.0=h3422bc3_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py38h3777fb4_0
  - pillow=8.4.0=py38h02acf36_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py38h10201cd_2
  - py=1.11.0=pyh6c4a22f_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pytest=6.2.5=py38h10201cd_2
  - python=3.8.12=hd949e87_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.0=cpu_py38ha3d347f_0
  - pytz=2021.3=pyhd8ed1ab_0
  - readline=8.1=hedafd6a_0
  - scikit-learn=1.0.2=py38h2cd4032_0
  - scipy=1.7.3=py38hd0c9ec0_0
  - setuptools=59.8.0=py38h10201cd_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h156473d_2
  - sqlite=3.37.0=h72a2b83_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=he1e0b03_1
  - toml=0.10.2=pyhd8ed1ab_0
  - torchvision=0.2.2=py_3
  - tornado=6.1=py38hea4295b_2
  - typing_extensions=4.0.1=pyha770c72_0
  - unicodedata2=14.0.0=py38hea4295b_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h642e427_1
  - zlib=1.2.11=hee7b306_1013
  - zstd=1.5.2=h861e0a7_0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/poison
