name: niteshade-dev
channels:
  - conda-forge
dependencies:
  - alabaster=0.7.12=py_0
  - aom=3.3.0=h07bb92c_1
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h33210d7_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=h1c322ee_7
  - brotli-bin=1.0.9=h1c322ee_7
  - brotlipy=0.7.0=py38h33210d7_1004
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2021.10.8=h4653dfc_0
  - certifi=2021.10.8=py38h10201cd_2
  - cffi=1.15.0=py38hc67bbb8_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cmarkgfm=0.8.0=py38h33210d7_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - commonmark=0.9.1=py_0
  - cryptography=36.0.2=py38h7f91714_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.6.0=py38hea55cf5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.15.2=py38h10201cd_3
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - ffmpeg=4.4.1=h2f96316_2
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fonttools=4.32.0=py38h33210d7_0
  - freetype=2.10.4=h17b34a0_1
  - future=0.18.2=py38h10201cd_5
  - gettext=0.19.8.1=h049c9fb_1008
  - giflib=5.2.1=h27ca646_2
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.6.13=h706517b_1
  - icu=70.1=h6b3803e_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.11.3=py38h10201cd_1
  - importlib_metadata=4.11.3=hd8ed1ab_1
  - importlib_resources=5.7.1=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.13.0=py38h2cb4d76_0
  - ipython=8.2.0=py38h10201cd_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.1=py38h10201cd_1
  - jinja2=3.1.1=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h1c322ee_1
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h10201cd_7
  - jupyter_client=7.2.2=pyhd8ed1ab_1
  - jupyter_console=6.4.3=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py38h10201cd_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - keyring=23.4.0=py38h10201cd_2
  - kiwisolver=1.4.2=py38h0f71543_1
  - lame=3.100=h27ca646_1001
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libblas=3.9.0=14_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1c322ee_7
  - libbrotlidec=1.0.9=h1c322ee_7
  - libbrotlienc=1.0.9=h1c322ee_7
  - libcblas=3.9.0=14_osxarm64_openblas
  - libcxx=13.0.1=h6a5c8ee_0
  - libdeflate=1.10=h3422bc3_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - libiconv=1.16=h642e427_0
  - liblapack=3.9.0=14_osxarm64_openblas
  - libopenblas=0.3.20=openmp_h2209c59_0
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.19.4=hccf11d3_0
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.3.0=h77dc3b6_3
  - libvpx=1.11.0=hc470f4d_3
  - libwebp=1.2.2=h0d20362_0
  - libwebp-base=1.2.2=h3422bc3_1
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.9.13=h97d9dda_0
  - libzlib=1.2.11=h90dfc92_1014
  - llvm-openmp=13.0.1=h455960f_1
  - lz4-c=1.9.3=hbdafb3b_1
  - markupsafe=2.1.1=py38h33210d7_1
  - matplotlib=3.5.1=py38h150bfb4_0
  - matplotlib-base=3.5.1=py38hb140015_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38hea4295b_1005
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=6.4.5=py38h10201cd_0
  - nbformat=5.3.0=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nettle=3.6=hc6a1b29_0
  - ninja=1.10.2=hc021e02_1
  - notebook=6.4.10=pyha770c72_0
  - numpy=1.22.3=py38hf29d37f_2
  - openh264=2.1.1=habe5f53_0
  - openjpeg=2.4.0=h062765e_1
  - openssl=1.1.1n=h90dfc92_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py38h55de146_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.0=py38h7ff1586_2
  - pip=22.0.4=pyhd8ed1ab_0
  - pkginfo=1.8.2=pyhd8ed1ab_0
  - pluggy=1.0.0=py38h10201cd_3
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - prompt_toolkit=3.0.29=hd8ed1ab_0
  - psutil=5.9.0=py38h33210d7_1
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.8=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38h33210d7_1
  - pysocks=1.7.1=py38h10201cd_5
  - pytest=7.1.1=py38h10201cd_1
  - python=3.8.13=h7e095e3_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=cpu_py38h1b6422d_0
  - pytz=2022.1=pyhd8ed1ab_0
  - pyzmq=22.3.0=py38h5f86631_2
  - readline=8.1=hedafd6a_0
  - readme_renderer=34.0=pyhd8ed1ab_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-toolbelt=0.9.1=py_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - rich=12.2.0=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py38h2cd4032_0
  - scipy=1.8.0=py38hd0c9ec0_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.1.0=py38h10201cd_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h156473d_2
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sphinx=4.5.0=pyh6c4a22f_0
  - sphinx_rtd_theme=1.0.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlite=3.38.2=h7e3ccbd_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - svt-av1=0.9.1=h07bb92c_0
  - terminado=0.13.3=py38h10201cd_1
  - testpath=0.6.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=he1e0b03_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchvision=0.12.0=cpu_py38h13a9dc5_1
  - tornado=6.1=py38h33210d7_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - twine=4.0.0=pyhd8ed1ab_0
  - typing_extensions=4.2.0=pyha770c72_0
  - unicodedata2=14.0.0=py38h33210d7_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - versioneer=0.22=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.0=py38h10201cd_0
  - x264=1!161.3030=h3422bc3_1
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.5=h642e427_1
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h90dfc92_1014
  - zstd=1.5.2=h861e0a7_0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/niteshade-dev
